-- Mentett SQL lekérdezések az Exporter modulhoz

CREATE TABLE IF NOT EXISTS exporter_queries (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    név VARCHAR(200) NOT NULL,
    query_sql TEXT NOT NULL,
    megjegyzés TEXT NULL,
    connection_id INT UNSIGNED NULL DEFAULT NULL,
    létrehozva DATETIME DEFAULT CURRENT_TIMESTAMP,
    módosítva DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
