-- Levélsablonok tábla létrehozása

CREATE TABLE IF NOT EXISTS finance_email_templates (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    név VARCHAR(255) NOT NULL,
    kód VARCHAR(100) NOT NULL UNIQUE,
    megjegyzés TEXT NULL,
    html_tartalom MEDIUMTEXT NOT NULL,
    létrehozva DATETIME DEFAULT CURRENT_TIMESTAMP,
    módosítva DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
