name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🚀 LFTP Sync (Mappakréalás nélkül)
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -c "
          open -u ${{ secrets.FTP_SERVER_USERNAME || secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
          set ftp:ssl-allow no;
          mirror --reverse \
                 --verbose \
                 --only-newer \
                 --ignore-time \
                 --exclude .git/ \
                 --exclude .cursor/ \
                 --exclude belepes/ \
                 --exclude lanueva/ \
                 ./ public_html/
          "